language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
notifications:
  irc:
    channels:
      - "chat.freenode.net#debt"
    template:
      - "%{author} updated the %{branch} branch of %{repository}"
      - "%{message} %{build_url}"
    skip_join: true
